// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/11/2025, 10:58:27 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/paulchou/Project/work/luci-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paulchou/Project/work/luci-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paulchou/Project/work/luci-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paulchou/Project/work/luci-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paulchou/Project/work/luci-web/plugins/**/*.{js,ts,mjs}","/Users/paulchou/Project/work/luci-web/composables/**/*.{js,ts,mjs}","/Users/paulchou/Project/work/luci-web/utils/**/*.{js,ts,mjs}","/Users/paulchou/Project/work/luci-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/paulchou/Project/work/luci-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/paulchou/Project/work/luci-web/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;