// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/3/12 18:44:19
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["E:/za-workspace/learn/luci-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/za-workspace/learn/luci-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/za-workspace/learn/luci-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/za-workspace/learn/luci-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/za-workspace/learn/luci-web/plugins/**/*.{js,ts,mjs}","E:/za-workspace/learn/luci-web/composables/**/*.{js,ts,mjs}","E:/za-workspace/learn/luci-web/utils/**/*.{js,ts,mjs}","E:/za-workspace/learn/luci-web/pages/about.vue","E:/za-workspace/learn/luci-web/pages/about.vue","E:/za-workspace/learn/luci-web/pages/contact.vue","E:/za-workspace/learn/luci-web/pages/contact.vue","E:/za-workspace/learn/luci-web/pages/downloads.vue","E:/za-workspace/learn/luci-web/pages/downloads.vue","E:/za-workspace/learn/luci-web/pages/index.vue","E:/za-workspace/learn/luci-web/pages/index.vue","E:/za-workspace/learn/luci-web/pages/news.vue","E:/za-workspace/learn/luci-web/pages/news.vue","E:/za-workspace/learn/luci-web/pages/products.vue","E:/za-workspace/learn/luci-web/pages/products.vue","E:/za-workspace/learn/luci-web/pages/services.vue","E:/za-workspace/learn/luci-web/pages/services.vue","E:/za-workspace/learn/luci-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/za-workspace/learn/luci-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/za-workspace/learn/luci-web/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;