// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/3/3 23:41:44
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/Works/nuxt3-luci-env/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Works/nuxt3-luci-env/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Works/nuxt3-luci-env/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Works/nuxt3-luci-env/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Works/nuxt3-luci-env/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Works/nuxt3-luci-env/plugins/**/*.{js,ts,mjs}","D:/Works/nuxt3-luci-env/composables/**/*.{js,ts,mjs}","D:/Works/nuxt3-luci-env/utils/**/*.{js,ts,mjs}","D:/Works/nuxt3-luci-env/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Works/nuxt3-luci-env/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Works/nuxt3-luci-env/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;